name: Check code and run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.6", "3.10"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install ".[testing]"
    - name: Analysing the code with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics    - uses: GabrielBB/xvfb-action@v1
    - run: pytest --version
    - name: Running tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: export PYTHONPATH=$(python -m site --user-site) pytest tests/ --ignore=tests/system/data/ --showlocals --verbose --show-capture=all --log-level=debug
